### ISSUE TITLE
cannot build ruby runtime

### ISSUE THREAD

**Issue by rabbah** [apache/openwhisk-runtime-ruby#31]
Travis is failing with:
```
mv: cannot stat 'incubator-openwhisk-runtime-go-golang1.11-1.13.0-incubating': No such file or directory

The command '/bin/sh -c curl -L "$PROXY_SOURCE" | tar xzf -   && mkdir -p src/github.com/apache   && mv incubator-openwhisk-runtime-go-golang1.11-1.13.0-incubating      src/github.com/apache/incubator-openwhisk-runtime-go   && cd src/github.com/apache/incubator-openwhisk-runtime-go/main   && CGO_ENABLED=0 go build -o /bin/proxy' returned a non-zero code: 1

Sat Aug 17 04:40:44 UTC 2019: Command 'docker build -t actionloop-ruby-v2.6 /home/travis/build/apache/openwhisk-runtime-ruby/core/ruby2.6ActionLoop' failed with exitCode 1, no more retries left, aborting...

:core:ruby2.6ActionLoop:distDocker FAILED

:core:ruby2.6ActionLoop:tagImage

Sat Aug 17 04:40:44 UTC 2019: Executing 'docker tag actionloop-ruby-v2.6 whisk/actionloop-ruby-v2.6:latest'

Error response from daemon: No such image: actionloop-ruby-v2.6:latest

Sat Aug 17 04:40:44 UTC 2019: Command 'docker tag actionloop-ruby-v2.6 whisk/actionloop-ruby-v2.6:latest' failed with exitCode 1, 2 retries left, retrying...

Sat Aug 17 04:40:44 UTC 2019: Executing 'docker tag actionloop-ruby-v2.6 whisk/actionloop-ruby-v2.6:latest'

Error response from daemon: No such image: actionloop-ruby-v2.6:latest

Sat Aug 17 04:40:44 UTC 2019: Command 'docker tag actionloop-ruby-v2.6 whisk/actionloop-ruby-v2.6:latest' failed with exitCode 1, 1 retries left, retrying...

Sat Aug 17 04:40:44 UTC 2019: Executing 'docker tag actionloop-ruby-v2.6 whisk/actionloop-ruby-v2.6:latest'

Error response from daemon: No such image: actionloop-ruby-v2.6:latest

Sat Aug 17 04:40:44 UTC 2019: Command 'docker tag actionloop-ruby-v2.6 whisk/actionloop-ruby-v2.6:latest' failed with exitCode 1, no more retries left, aborting...

:core:ruby2.6ActionLoop:tagImage FAILED
```

@sciabarracom do you know how to fix this?

**Comment by sciabarracom** [comment]
Yes I mentioned on the mailing list this problem, we need a new release of the sources. In the meanwhile I can work around building straight from git.

**Comment by sciabarracom** [comment]
check PR#33

**Comment by sciabarracom** [comment]
Hm the build now it is failing for a reason related to akka. 

Detected possible incompatible versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using, e.g. if you use [2.5.22] all other modules that are released together MUST be of the same version. Make sure you're using a compatible set of libraries. Possibly conflicting versions [2.5.3, 2.5.22, 2.5.7] in libraries [akka-cluster-metrics:2.5.3, akka-protobuf:2.5.22, akka-actor:2.5.22, akka-slf4j:2.5.22, akka-remote:2.5.7, akka-cluster:2.5.7, akka-distributed-data:2.5.3, akka-stream:2.5.22, akka-stream-testkit:2.5.22, akka-cluster-tools:2.5.3]

Can you suggest a fix?

**Comment by dgrove-oss** [comment]
I thought I got a successful build in #30 that fixed this.  Been on vacation. I will take a look once I'm unburied...

**Comment by rabbah** [comment]
I don't know how these tests passed in the past - the stdout sentinel is currently only emitted when the server is shutdown and so all the tests which check for the stdout sentinel fail.

**Comment by dgrove-oss** [comment]
The github settings for this repo are not right; allowing merges without successful travis runs.  Guess we should not ask infra to fix that until we actually can get a clean run though..

**Comment by rabbah** [comment]
Yep I noticed and was using it to our advantage right now.
